### ISSUE TITLE
other formats: csv, json

### ISSUE THREAD

**Issue by jbkunst** [cristianst85/GeoNuclearData#1]
Hi @cristianst85 !

There's a possibility you can put the data in other formats for easy import to other platforms? I can parse the data or create a db but I think this can be help other people use this data.

Thanks for the repo :wink:.

**Comment by cristianst85** [comment]
Hello, @jbkunst! 

Of course I can 😉

**Comment by jbkunst** [comment]
Thanks! :wink:

**Comment by radhoo** [comment]
Guys, thanks for this. I got your comments notification and it was all I needed to finally add this NPP data to the www.uradmonitor.com

**Comment by cristianst85** [comment]
I've published the data in both formats (JSON and CSV). Also, data in _denormalized_ form is available.

@jbkunst, could you please review it and let me know if there are any changes you would like me to make before I close this? Thanks.

**Comment by jbkunst** [comment]
Hi @cristianst85 ,

I readed the csv and the json without problems, the only difference is the date fields, the csv is like "yyyy-mm-dd" and the json the format is "yyyy-mm-ddThh:mm:ss+03:00".

Thanks so much for this! You can close the issue.

**Comment by cristianst85** [comment]
I've removed the time component for `ConstructionStartAt`, `OperationalFrom `and `OperationalTo` properties in the json files to have consistent data across formats.

Thank you for your feedback!
